### PR TITLE
[WIP] Redesign 

### PR DESCRIPTION
**Pull request by mayagao**
https://github.com/documentationjs/documentation/issues/115#

screen shot 2015-07-13 at 12 45 21 am

### CODE REVIEW

**Comment by knownasilya** [comment]
I think you should just release this as another theme :+1: I'm sure @tmcw would be totally for that.

**Comment by mayagao** [comment]
oops completely forgot about this pr. @tmcw you think i should release as another theme? maybe i should close this...

**Comment by knownasilya** [comment]
@mayagao if you don't have time to make it into it's own module/theme, I'm totally willing (obviously giving you and @tmcw credit for the work) to do it.

**Comment by mayagao** [comment]
theme here https://github.com/documentationjs/documentation-theme-light

**Pull request closed without merging**
